"""
Django settings for artikate_studio project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import sys
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SILKY_ANALYZE_QUERIES = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@ff648$b-b2c)tmc&g8(y-t4h#vob_d(ri-+yufm8fh7bc7b%j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ---------------------------------------------------------------------------
# Django Silk Configuration
# ---------------------------------------------------------------------------

# Disable EXPLAIN/ANALYZE queries.
# This prevents Silk from executing an additional EXPLAIN QUERY PLAN statement
# for every SQL query, which would interfere with assertNumQueries() tests.
SILKY_ANALYZE_QUERIES = False

# Enable Python profiling for request-level performance analysis.
SILKY_PYTHON_PROFILER = True

# Prevent very large request/response bodies from being stored by Silk.
SILKY_MAX_REQUEST_BODY_SIZE = 1024
SILKY_MAX_RESPONSE_BODY_SIZE = 1024
TESTING = "test" in sys.argv
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'orders',
    "jobs",
    "tenant",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "tenant.middleware.TenantMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not TESTING:
    INSTALLED_APPS.append("silk")
if not TESTING:
    MIDDLEWARE.insert(
        0,
        "silk.middleware.SilkyMiddleware",
    )
ROOT_URLCONF = 'artikate_studio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'artikate_studio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'




# # ---------------------------------------------------------------------------
# # Celery / Redis configuration
# # ---------------------------------------------------------------------------

# CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"

# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/1"


# # Acknowledge a task only after it finishes successfully.
# #
# # If the worker crashes while processing the task, the task remains
# # unacknowledged and can be delivered again.
# CELERY_TASK_ACKS_LATE = True


# # If the child worker process is unexpectedly killed, reject the
# # unacknowledged task so that the broker can requeue it.
# CELERY_TASK_REJECT_ON_WORKER_LOST = True


# # Each worker process reserves only one task at a time.
# #
# # This prevents one worker from reserving a large number of jobs and
# # improves fairness when processing large bursts.
# CELERY_WORKER_PREFETCH_MULTIPLIER = 1


# # Keep broker connections retryable during application startup.
# CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True



# ---------------------------------------------------------------------------
# Celery configuration
# ---------------------------------------------------------------------------

# CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"

# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/1"

CELERY_TASK_ACKS_LATE = True

CELERY_TASK_REJECT_ON_WORKER_LOST = True

CELERY_WORKER_PREFETCH_MULTIPLIER = 1

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True



# ---------------------------------------------------------------------------
# Email queue settings
# ---------------------------------------------------------------------------



# The production requirement is a global maximum of 200 email jobs in every
# rolling 60-second window.  Environment variables make a shorter window
# available for local experiments without changing the committed default.
EMAIL_RATE_LIMIT = int(
    os.getenv("EMAIL_RATE_LIMIT", "200")
)

EMAIL_RATE_WINDOW_SECONDS = float(
    os.getenv("EMAIL_RATE_WINDOW_SECONDS", "60")
)



# EMAIL_RATE_LIMIT_REDIS_URL = "redis://127.0.0.1:6379/2"

# EMAIL_DEAD_LETTER_REDIS_URL = "redis://127.0.0.1:6379/3"


# Print emails to the console during local development.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = "noreply@example.com"



# Celery message broker for this assessment project.
CELERY_BROKER_URL = "redis://127.0.0.1:6379/4"

# Celery task results.
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/5"

# Sliding-window email rate limiter.
EMAIL_RATE_LIMIT_REDIS_URL = "redis://127.0.0.1:6379/6"

# Permanently failed email jobs.
EMAIL_DEAD_LETTER_REDIS_URL = "redis://127.0.0.1:6379/7"
