import json
import uuid

from django.core.management.base import BaseCommand, CommandError

from jobs.pending_queue import (
    DEAD_LETTER_EMAIL_QUEUE_KEY,
    DISPATCHER_LOCK_KEY,
    PENDING_EMAIL_QUEUE_KEY,
    PROCESSING_EMAIL_QUEUE_KEY,
    clear_queue_metrics,
    dispatcher_is_locked,
    get_dead_letter_count,
    get_pending_count,
    get_processing_count,
    get_queue_metrics,
    get_redis_client,
    record_submitted,
    start_queue_run,
)
from jobs.rate_limiter import (
    RATE_LIMIT_KEY,
    get_rate_limit,
    get_rate_limit_status,
)
from jobs.tasks import dispatch_pending_emails


class Command(BaseCommand):
    help = (
        "Submit a clean, observable batch for the live Section 2 recording."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--count",
            type=int,
            default=250,
            help=(
                "Number of jobs to submit (default: 250; enough to show "
                "the required 200/minute throttle)."
            ),
        )
        parser.add_argument(
            "--fail-once-index",
            type=int,
            default=1,
            help=(
                "One-based job index that fails once and then retries. "
                "Use 0 to disable (default: 1)."
            ),
        )
        parser.add_argument(
            "--reset",
            action="store_true",
            help=(
                "Clear the custom queue, rate-limit state, dead-letter "
                "queue, and demo metrics before submitting the batch."
            ),
        )

    def _queue_has_state(self):
        return any(
            (
                get_pending_count(),
                get_processing_count(),
                get_dead_letter_count(),
                dispatcher_is_locked(),
            )
        )

    def _demo_metrics_have_state(self):
        metrics = get_queue_metrics()
        return any(
            (
                metrics["submitted"],
                metrics["dispatched"],
                metrics["completed"],
                metrics["retries"],
                metrics["failed"],
                get_rate_limit_status()["used"],
            )
        )

    def _reset_demo_state(self):
        get_redis_client().delete(
            PENDING_EMAIL_QUEUE_KEY,
            PROCESSING_EMAIL_QUEUE_KEY,
            DEAD_LETTER_EMAIL_QUEUE_KEY,
            DISPATCHER_LOCK_KEY,
            RATE_LIMIT_KEY,
        )
        clear_queue_metrics()

    def handle(self, *args, **options):
        count = options["count"]
        fail_once_index = options["fail_once_index"]
        reset = options["reset"]

        if count < 1:
            raise CommandError("--count must be at least 1.")

        if fail_once_index < 0 or fail_once_index > count:
            raise CommandError(
                "--fail-once-index must be 0 or a job number in the batch."
            )

        if reset:
            self._reset_demo_state()
        elif (
            self._queue_has_state()
            or self._demo_metrics_have_state()
        ):
            raise CommandError(
                "Existing queue, rate-limit, or demo-metric state was found. "
                "Run with --reset for a fresh recording, or inspect it with "
                "queue_status first."
            )

        rate_limit, window_seconds = get_rate_limit()
        redis_client = get_redis_client()
        pipeline = redis_client.pipeline()
        retry_job_id = None

        start_queue_run()

        for index in range(1, count + 1):
            job_id = f"live-demo-{index:03d}-{uuid.uuid4().hex[:8]}"
            fail_once = index == fail_once_index

            if fail_once:
                retry_job_id = job_id

            pipeline.rpush(
                PENDING_EMAIL_QUEUE_KEY,
                json.dumps(
                    {
                        "job_id": job_id,
                        "email": f"live-demo-{index}@example.com",
                        "subject": f"Live queue demo email {index}",
                        "message": (
                            "This message was generated by the Section 2 "
                            "live-system demo command."
                        ),
                        "fail_once": fail_once,
                        "always_fail": False,
                    }
                ),
            )

        pipeline.execute()
        record_submitted(count)

        dispatcher_result = dispatch_pending_emails.delay()

        self.stdout.write(
            self.style.SUCCESS(
                "\nLIVE SYSTEM DEMO STARTED\n"
                "============================================================"
            )
        )
        self.stdout.write(f"Submitted jobs     : {count}")
        self.stdout.write(
            f"Rate limit         : {rate_limit} jobs / "
            f"{window_seconds:g} seconds"
        )
        self.stdout.write(
            f"Pending immediately: {get_pending_count()}"
        )
        self.stdout.write(
            f"Dispatcher task ID : {dispatcher_result.id}"
        )

        if retry_job_id:
            self.stdout.write(
                "Intentional retry : "
                f"{retry_job_id} will fail once, then retry after 5 seconds."
            )
        else:
            self.stdout.write("Intentional retry : disabled")

        if count <= rate_limit:
            self.stdout.write(
                self.style.WARNING(
                    "This batch is not larger than the rate limit, so it "
                    "will not demonstrate throttling. Use a count above "
                    f"{rate_limit}."
                )
            )

        self.stdout.write(
            "\nIn another terminal, run:\n"
            "  python manage.py queue_status --watch --interval 1\n"
            "The monitor shows pending/processing/dead-letter counts, "
            "rate-window occupancy, retry totals, and the maximum observed "
            "rolling-window dispatch count."
        )
